[package]
name = "rust"
version = "0.1.0"
authors = ["Tyler Stewart <hello@tylerstewart.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
reqwest = "0.9.22"
